// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAws7tw3sOnItGycoAmf6sq6pWa39XUsUk',
    appId: '1:808988324914:web:5f67901462352dec1f782b',
    messagingSenderId: '808988324914',
    projectId: 'micard-985b2',
    authDomain: 'micard-985b2.firebaseapp.com',
    storageBucket: 'micard-985b2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGQ4Axj30B-1Q_cIe_sHNQnOkBK7l3CnA',
    appId: '1:808988324914:android:14ea352497b4f9301f782b',
    messagingSenderId: '808988324914',
    projectId: 'micard-985b2',
    storageBucket: 'micard-985b2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZ8Y4eSdp734War_-SC4wb4bDDvtGrUTc',
    appId: '1:808988324914:ios:a09eeaeb9009b54d1f782b',
    messagingSenderId: '808988324914',
    projectId: 'micard-985b2',
    storageBucket: 'micard-985b2.appspot.com',
    iosClientId: '808988324914-d3qpi0ltv37jbl68gfhbib1u39al72gc.apps.googleusercontent.com',
    iosBundleId: 'com.example.businessCard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZ8Y4eSdp734War_-SC4wb4bDDvtGrUTc',
    appId: '1:808988324914:ios:98983a451925351d1f782b',
    messagingSenderId: '808988324914',
    projectId: 'micard-985b2',
    storageBucket: 'micard-985b2.appspot.com',
    iosClientId: '808988324914-1q4crarjh0gb68gjumt9l01hq3ujukmv.apps.googleusercontent.com',
    iosBundleId: 'com.example.businessCard.RunnerTests',
  );
}
